github.com:
    users:
        JohnBLaPlante:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: JohnBLaPlante
